optimizer:
  name: "MIPRO"
  params:
    auto: "medium"          # bump to "heavy" if you can spend more compute
    max_bootstrapped_demos: 3
    max_labeled_demos: 5
    init_temperature: 1.0
    verbose: false
    track_stats: true
    seed: 9


module:
  use_cot: false

logging:
  level: "INFO"
  enable_llm_logger: false